<?php

use yii\bootstrap\ButtonDropdown;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', $pageName);
?>
<div class="alt hide">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    Undelete <?php echo $pageName; ?> item successfully.
</div>
<div class="margin-top-10">
    <div class="portlet light ">
        <p class="text-right">
            <?php if (isset($owner_id)): ?>
                <?= Html::a(Yii::t('app', 'Create ' . $pageName), ['create', 'owner_id' => $owner_id], ['class' => 'btn btn-success']) ?>
            <?php else: ?>
                <?= Html::a(Yii::t('app', 'Create ' . $pageName), ['create'], ['class' => 'btn btn-success']) ?>
            <?php endif; ?>

        </p>
        </p>
        <div class="portlet-body">
            <div class="alt-undelete">

            </div>
            <?php \yii\widgets\Pjax::begin(['id' => str_replace(" ", "", $pageName), 'timeout' => false, 'linkSelector' => 'a.pjax', 'enablePushState' => false, 'clientOptions' => ['method' => 'GET']]); ?>
            <?php echo \common\widgets\Alert::widget(); ?>
            <?php if (Yii::$app->session->hasFlash('msg_success')): ?>
                <div class="alert alert-success">
                    <button class="close" data-close="alert"></button>
                    <?= Yii::$app->session->getFlash('msg_success') ?>
                </div>
            <?php endif; ?>

            <div class="table-responsive" style="overflow: visible;">
                <?php
                $classHide = '';
                if (!empty($deleted)) {
                    $classHide = 'hide';
                }
                // action for gridview
                $actions = [
                    'class' => 'yii\grid\ActionColumn',
                    'headerOptions' => ['style' => 'width: 20%;'],
                    'header' => 'Action',
                    'template' => '{all}',
                    'buttons' => [
                        'all' => function($url, $model, $key) {
                            $pageUrl = $model->modelPageUrl;
                            $pageName = $model->modelPageName;
                            $visible = true;
                            if ($model->status == $model::STATUS_DELETED) {
                                $visible = false;
                            }

                            $delete_url = Yii::$app->urlManager->createUrl('/settings/' . $pageUrl . '/delete?id=' . $key);
                            $undelete_url = Yii::$app->urlManager->createAbsoluteUrl('/settings/' . $pageUrl . '/undelete?id=' . $key);

                            return ButtonDropdown::widget([
                                        'containerOptions' => [
                                            'class' => ''
                                        ],
                                        'encodeLabel' => false,
                                        'label' => 'Options',
                                        'dropdown' => [
                                            'encodeLabels' => false,
                                            'items' => [
                                                [
                                                    'label' => \Yii::t('yii', 'View'),
                                                    'url' => ['view', 'id' => $key],
                                                    'visible' => $visible,
                                                ],
                                                [
                                                    'label' => \Yii::t('yii', 'Update'),
                                                    'url' => ['update', 'id' => $key],
                                                    'visible' => $visible,
                                                ],
                                                [
                                                    'label' => \Yii::t('yii', 'Delete'),
                                                    'options' => [
                                                        'onclick' => "if (confirm('Are you sure you want to delete this item?')) {
                                                            $.ajax('" . $delete_url . "', {
                                                                type: 'POST',
                                                                dataType: 'JSON'
                                                            }).done(function(data) {
                                                                console
                                                                 $.pjax.reload({container: '#" . str_replace(" ", "", $pageName) . "'});
                                                            });
                                                }; return false;"
                                                    ],
                                                    'url' => [''],
                                                    'visible' => $visible,
                                                ],
                                                [
                                                    'label' => \Yii::t('yii', 'Undelete'),
                                                    'options' => [
                                                        'onclick' => "if (confirm('Are you sure you want to undelete this item?')) {
                                                            $.ajax('" . $undelete_url . "', {
                                                                type: 'POST',
                                                                dataType: 'JSON'
                                                            }).done(function(data) {
                                                                 $.pjax.reload({container: '#" . str_replace(" ", "", $pageName) . "'});
                                                                  $('.pjax-tab-delete').trigger('click');
                                                                  var alt = '<div class=\"alert-success alert\" >'+$('.alt').html()+'</div>';
                                                                  $('.alt-undelete').html(alt);
                                                            });
                                                    }; return false;"
                                                    ],
                                                    'url' => [''],
                                                    'visible' => !$visible,
                                                ]
                                            ],
                                        ],
                                        'options' => [
                                            'class' => 'btn-default btn-xs',
                                        ],
                                        'split' => true,
                            ]);
                        },
                    ]
                ];
                // column for grid view
                $columns = [
                    [
                        'class' => 'yii\grid\SerialColumn',
                        'contentOptions' => [
                            'width' => '3%'
                        ]
                    ],
                    [
                        'attribute' => 'name',
                        'filterInputOptions' => [
                            'class' => 'form-control',
                        ],
                        'format' => 'html',
                        'value' => function($data) {
                            return Html::a($data->name, ['view', 'id' => $data->id]);
                        },
                    ],
                    [
                        'attribute' =>'price',
                        'filterInputOptions' => [
                            'class' =>'form-control',
                        ],
                        'value' => function($data) {
                            $htmlUtils = new \common\components\HtmlUtils();
                            return $htmlUtils->asPrice($data->price, Yii::$app->user->identity->currency_id);
                        }
                    ],
                    [
                        'attribute' => 'price_type',
                        'filterInputOptions' => [
                            'class' => 'form-control',
                        ],
                        'format' => 'html',
                        'value' => function($data) {
                            return Html::a(ucfirst($data->price_type), ['view', 'id' => $data->id]);
                        },
                    ],
                    [
                        'attribute' => 'fixed_price',
                        'filterInputOptions' => [
                            'class' => 'form-control',
                        ],
                        'format' => 'html',
                        'value' => function($data) {
                            return Html::a($data->fixed_price, ['view', 'id' => $data->id]);
                        },
                    ],
                    [
                        'attribute' => 'created',
                        'filterInputOptions' => [
                            'class' => 'form-control',
                        ],
                        'value' => function($data) {
                            return Yii::$app->formatter->asDate($data->created);
                        },
                        'filter' => yii\jui\DatePicker::widget([
                            'model' => $model,
                            'attribute' => 'created',
                            'dateFormat' => common\components\CommonUtils::getParameter('formatter.datePicker', 'php:d-M-Y'),
                            'options' => [
                                'class' => 'form-control',
                            ],
                            'value' => function($model) {
                                return Yii::$app->formatter->asDateByTimezone($model->created, $model->owner_id, 'm/d/Y');
                            }
                        ]),
                    ],
                    $actions,
                ];

                echo GridView::widget([
                    'dataProvider' => $dataProvider,
                    'filterRowOptions' => ['class' => 'yellow'],
                    'filterModel' => $model,
                    'tableOptions' => ['class' => 'table table-striped table-hover'],
                    'layout' => "{errors}\n{items}\n{pager}",
                    'columns' => $columns
                ]);
                ?>
                <p class="text-right">
                <?php if (isset($owner_id) && !empty($owner_id)): ?>
                        <?php echo Html::a('Active', ['index', 'owner_id' => $owner_id], ['class' => 'pjax']) ?>
                        &nbsp;|&nbsp;
                        <?php echo Html::a('Deleted', ['index', 'owner_id' => $owner_id, 'deleted' => -1], ['class' => 'pjax pjax-tab-delete']) ?>
                    <?php else: ?>
                        <?php echo Html::a('Active', ['index'], ['class' => 'pjax']) ?>
                        &nbsp;|&nbsp;
                        <?php echo Html::a('Deleted', ['index', 'deleted' => 1], ['class' => 'pjax pjax-tab-delete']) ?>
                    <?php endif; ?>
                </p>
            </div>
<?php \yii\widgets\Pjax::end(); ?>
        </div>
    </div>
</div>

<?php
$this->registerJs("var elm = $('div.alert-success');
    if(elm.length >0 ) {
        setTimeout(function(){
            elm.addClass('hide');
        }, 6000);
    }

    $(document).on('click','button.close',function(){
        elm.addClass('hide');
    });");
?>
